
INSERT INTO TICKETING_CLASSE (NOM) VALUES ('AFFAIRE');
INSERT INTO TICKETING_CLASSE (NOM) VALUES ('ECONOMIQUE');

INSERT INTO TICKETING_STATUT_RESERVATION (NOM) VALUES ('CONFIRMEE');
INSERT INTO TICKETING_STATUT_RESERVATION (NOM) VALUES ('ANNULEE');
INSERT INTO TICKETING_STATUT_RESERVATION (NOM) VALUES ('PAYEE');

INSERT INTO TICKETING_ADMIN (USERNAME, PASSWORD) VALUES ('admin', 'admin123');
INSERT INTO TICKETING_UTILISATEUR (USERNAME, PASSWORD) VALUES ('user', 'user123');

INSERT INTO TICKETING_COMPANY(NOM) VALUES ('Air Madagascar');
INSERT INTO TICKETING_COMPANY(NOM) VALUES ('Air France');


INSERT INTO TICKETING_AVION (MODELE, DATE_FABRICATION,COMPANY_ID) VALUES ('Boeing 737-800',TO_DATE('2015-03-15', 'YYYY-MM-DD') ,1  );
INSERT INTO TICKETING_AVION (MODELE, DATE_FABRICATION,COMPANY_ID) VALUES ('Airbus A320', TO_DATE('2018-06-20', 'YYYY-MM-DD'),2  );

INSERT INTO TICKETING_SIEGE(AVION_ID , NBR , CLASSE_ID,PRIX)VALUES(1,50,1,500);
INSERT INTO TICKETING_SIEGE(AVION_ID , NBR , CLASSE_ID,PRIX)VALUES(1,100,2 ,300);
INSERT INTO TICKETING_SIEGE(AVION_ID , NBR , CLASSE_ID,PRIX)VALUES(2,25,1 ,400 );
INSERT INTO TICKETING_SIEGE(AVION_ID , NBR , CLASSE_ID,PRIX)VALUES(2,75,2 , 250);

INSERT INTO TICKETING_VILLE (NOM) VALUES ('Antananarivo');
INSERT INTO TICKETING_VILLE (NOM) VALUES ('Paris CDG');
INSERT INTO TICKETING_VILLE (NOM) VALUES ('Mauritus');
INSERT INTO TICKETING_VILLE (NOM) VALUES ('Addis Abeba');

INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Bebe', 0, 3, 0);         
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Enfant', 4, 12, 50);     
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Adolescent', 13, 18, 75);
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Jeune', 19, 30, 100);    
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Adulte', 31, 60, 100);   
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Vieux', 61, 80, 80);     
INSERT INTO TICKETING_CATEGORIE_AGE (NOM, BORNE_MIN, BORNE_MAX, POURCENTAGE_PAYER)
VALUES ('Retraite', 81, 200, 70); 
    

INSERT INTO TICKETING_VOL (AVION_ID, VILLE_DEPART_ID, VILLE_ARRIVEE_ID, DATE_HEURE_DEPART) 
VALUES (1, 1, 4, TO_TIMESTAMP('2025-09-05 08:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TICKETING_VOL (AVION_ID, VILLE_DEPART_ID, VILLE_ARRIVEE_ID, DATE_HEURE_DEPART) 
VALUES (2, 2, 3, TO_TIMESTAMP('2025-09-15 21:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TICKETING_PROMOTION(VOL_ID, CLASSE_ID, NBR_SIEGE, REDUCTION, DATE_BUTOIRE, PRIX, NBR_SIEGE_DISPO)
VALUES (1, 2, 4, 20, TO_DATE('2025-08-27', 'YYYY-MM-DD'), 200, 4);

INSERT INTO TICKETING_PROMOTION(VOL_ID, CLASSE_ID, NBR_SIEGE, REDUCTION, DATE_BUTOIRE, PRIX, NBR_SIEGE_DISPO)
VALUES (1, 2, 2, 10, TO_DATE('2025-09-03', 'YYYY-MM-DD'), 300, 2);

INSERT INTO TICKETING_PROMOTION(VOL_ID, CLASSE_ID, NBR_SIEGE, REDUCTION, DATE_BUTOIRE, PRIX, NBR_SIEGE_DISPO)
VALUES (2, 2, 3, 20, TO_DATE('2025-09-05', 'YYYY-MM-DD'), 350, 3);

INSERT INTO TICKETING_PROMOTION(VOL_ID, CLASSE_ID, NBR_SIEGE, REDUCTION, DATE_BUTOIRE, PRIX, NBR_SIEGE_DISPO)
VALUES (2, 2, 1, 10, TO_DATE('2025-09-13', 'YYYY-MM-DD'), 400, 1);


INSERT INTO TICKETING_RESERVATION (UTILISATEUR_ID, VOL_ID, DATE_RESERVATION, STATUT_ID, 
                                   CATEGORIE_AGE_ID, NB_SIEGES, CLASSE_ID, REDUCTION, POURCENTAGE_PAYER, PRIX_PAYER)
VALUES (1, 1, TO_DATE('2025-08-20', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-08-21', 'YYYY-MM-DD'), 1, 0, 0, 0, 0, 0, 0);

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-08-21', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-08-28', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-08-29', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0);

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-09-01', 'YYYY-MM-DD'), 1, 0, 0, 0, 0, 0, 0); 

INSERT INTO TICKETING_RESERVATION VALUES (1, 1, TO_DATE('2025-09-02', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 


INSERT INTO TICKETING_RESERVATION VALUES (1, 2, TO_DATE('2025-09-01', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0);

INSERT INTO TICKETING_RESERVATION VALUES (1, 2, TO_DATE('2025-09-02', 'YYYY-MM-DD'), 1, 0, 0, 0, 0, 0, 0);

INSERT INTO TICKETING_RESERVATION VALUES (1, 2, TO_DATE('2025-09-08', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 

INSERT INTO TICKETING_RESERVATION VALUES (1, 2, TO_DATE('2025-09-10', 'YYYY-MM-DD'), 3, 0, 0, 0, 0, 0, 0); 


COMMIT;